# MongoDB 설정
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/eatmoji

# GPT FastAPI 서버 설정
gpt:
  url: http://localhost:8000/gpt/recommendation

# AWS S3 설정
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ${REGION}
    s3:
      bucket: ${S3_BUCKET_NAME}
